# Generated by Django 3.1.7 on 2021-03-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('available', models.IntegerField()),
                ('image', models.CharField(max_length=1000)),
                ('simple_image', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
